baseURL = 'https://probbi.com/'
languageCode = 'hu'
title = 'probbi'
theme = 'PaperMod'

[menu]
    [[menu.main]]
        name = "Blog"
        url = "/posts/"
        weight = 10

    [[menu.main]]
        name = "TryHackMe"
        url = "/tryhackme/"
        weight = 20

    [[menu.main]]
        name = "Tools"
        url = "/tryhackme/security-tools/"
        weight = 30

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"

[params]
    mainSections = ["posts"]    # Itt üres volt, írd be a "posts"-t, hogy lásd a cikkeket!
    ShowCodeCopyButtons = true
    author = "probbi"           # Emlékszel, az RSS hiba miatt ez is kellhet
